accepted = [
	"Unlicense",    # https://spdx.org/licenses/Unlicense
	"CC0-1.0",      # https://spdx.org/licenses/CC0-1.0
	"MIT",          # https://spdx.org/licenses/MIT
	"BSL-1.0",      # https://spdx.org/licenses/BSL-1.0
	"BSD-3-Clause", # https://spdx.org/licenses/BSD-3-Clause
	"Zlib",         # https://spdx.org/licenses/Zlib
	"Apache-2.0",   # https://spdx.org/licenses/Apache-2.0
	"Unicode-3.0",  # https://spdx.org/licenses/Unicode-3.0
]

targets = ["x86_64-unknown-linux-gnu"]

no-clearly-defined = true

[final-countdown]
accepted = ["AGPL-3.0-or-later"]

# Only used in the build script, not actually distributed
[cssparser]
accepted = ["MPL-2.0"]

[cssparser-color]
accepted = ["MPL-2.0"]

[cssparser-macros]
accepted = ["MPL-2.0"]

[dtoa-short]
accepted = ["MPL-2.0"]

[lightningcss]
accepted = ["MPL-2.0"]

[lightningcss-derive]
accepted = ["MPL-2.0"]

[parcel_selectors]
accepted = ["MPL-2.0"]

[libbz2-rs-sys]
accepted = ["bzip2-1.0.6"]
